import type { CampEvent, Facility } from "./types.ts";

export const REGION_CENTER = {
  lat: 25.1986,
  lng: 91.8785,
  name: "Mawlynnong Community Health Block",
};

export const SYNTHETIC_FACILITIES: Facility[] = [
  {
    id: "F-DEMO-001",
    name: "Mawlynnong District Hospital (demo)",
    type: "hospital",
    coordinates: { lat: 25.2001, lng: 91.8802, accuracyMeters: 10, source: "gps" },
    address: "District Hospital Road, Mawlynnong",
    villageCode: "MWL",
    phone: "+913612000001",
    capabilities: {
      emergency: true,
      icu: true,
      oxygen: true,
      paediatrics: true,
      maternity: true,
      surgery: true,
      ambulance: true,
      pharmacy: true,
      mental_health: true,
      diagnostics: true,
    },
    schemes: ["ayushman", "pmjay", "abdm_hfr", "state_nhm"],
    openNow: true,
    verification: "verified",
    verificationSource: "ABDM Health Facility Registry (demo)",
    verifiedAt: "2026-07-01T00:00:00Z",
    expiresAt: "2027-07-01T00:00:00Z",
    externalId: "HFR-DEMO-001",
    sourceUrl: "https://facility.hfr.abdm.gov.in (demo)",
    lastFetchedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "F-DEMO-002",
    name: "Pynursla CHC (demo)",
    type: "chc",
    coordinates: { lat: 25.1842, lng: 91.9023, accuracyMeters: 15, source: "gps" },
    address: "Community Health Centre, Pynursla",
    villageCode: "PYN",
    phone: "+913612000002",
    capabilities: {
      emergency: true,
      icu: false,
      oxygen: true,
      paediatrics: true,
      maternity: true,
      surgery: false,
      ambulance: true,
      pharmacy: true,
      mental_health: false,
      diagnostics: true,
    },
    schemes: ["state_nhm", "pmjay"],
    openNow: true,
    verification: "verified",
    verificationSource: "State NHM directory (demo)",
    verifiedAt: "2026-06-15T00:00:00Z",
    externalId: "CHC-DEMO-002",
    sourceUrl: "https://nhm.meg.gov.in (demo)",
    lastFetchedAt: "2026-07-20T00:00:00Z",
  },
  {
    id: "F-DEMO-003",
    name: "North Ridge PHC (demo)",
    type: "phc",
    coordinates: { lat: 25.221, lng: 91.861, accuracyMeters: 20, source: "gps" },
    address: "Primary Health Centre, North Ridge",
    villageCode: "NRT",
    phone: "+913612000003",
    capabilities: {
      emergency: false,
      icu: false,
      oxygen: false,
      paediatrics: true,
      maternity: true,
      surgery: false,
      ambulance: false,
      pharmacy: true,
      mental_health: false,
      diagnostics: false,
    },
    schemes: ["state_nhm"],
    openNow: true,
    verification: "verified",
    verificationSource: "District health administration (demo)",
    verifiedAt: "2026-05-10T00:00:00Z",
    externalId: "PHC-DEMO-003",
    sourceUrl: "https://nhm.meg.gov.in (demo)",
    lastFetchedAt: "2026-07-20T00:00:00Z",
  },
  {
    id: "F-DEMO-004",
    name: "Pynursla Pradhan Mantri Jan Aushadhi Kendra",
    type: "pharmacy",
    coordinates: { lat: 25.1855, lng: 91.9015, accuracyMeters: 10, source: "gps" },
    address: "Main Market, Pynursla",
    villageCode: "PYN",
    phone: "+919863000001",
    capabilities: {
      emergency: false,
      icu: false,
      oxygen: false,
      paediatrics: false,
      maternity: false,
      surgery: false,
      ambulance: false,
      pharmacy: true,
      mental_health: false,
      diagnostics: false,
    },
    schemes: ["pmbjp", "jan_aushadhi"],
    openNow: true,
    verification: "verified",
    verificationSource: "PMBJP Kendra Registry (demo)",
    verifiedAt: "2026-08-01T00:00:00Z",
    externalId: "PMBJP-PYN-01",
    sourceUrl: "https://janaushadhi.gov.in (demo)",
    lastFetchedAt: "2026-08-10T00:00:00Z",
  },
];

export const SYNTHETIC_CAMPS: CampEvent[] = [
  {
    id: "CAMP-DEMO-001",
    title: "Mawlynnong Community Health & Immunization Camp",
    name: "Mawlynnong Community Health & Immunization Camp",
    villageCode: "MWL",
    villageName: "Mawlynnong",
    coordinates: { lat: 25.201, lng: 91.879 },
    startDate: "2026-09-20",
    endDate: "2026-10-15",
    timings: "09:00 AM - 04:00 PM",
    organizer: "District Mobile Medical Unit (MMU)",
    services: ["General OPD", "BP & Sugar Screening", "Childhood Immunization", "Free Essential Generics"],
    contactPhone: "+919863000010",
    status: "active",
  },
  {
    id: "CAMP-DEMO-002",
    title: "Pynursla Maternal & Child Health Outreach",
    name: "Pynursla Maternal & Child Health Outreach",
    villageCode: "PYN",
    villageName: "Pynursla",
    coordinates: { lat: 25.186, lng: 91.903 },
    startDate: "2026-09-25",
    endDate: "2026-10-05",
    timings: "10:00 AM - 03:00 PM",
    organizer: "NHM Sub-Divisional Team",
    services: ["Antenatal Checkups", "Anemia Screening", "Ultrasound Triage", "Nutritional Counseling"],
    contactPhone: "+919863000011",
    status: "active",
  },
  {
    id: "CAMP-EXPIRED",
    title: "Old Monsoon Dengue Awareness Camp",
    name: "Old Monsoon Dengue Awareness Camp",
    villageCode: "MWL",
    villageName: "Mawlynnong",
    coordinates: { lat: 25.201, lng: 91.879 },
    startDate: "2026-08-01",
    endDate: "2026-08-15",
    timings: "09:00 AM - 02:00 PM",
    organizer: "Vector Control Cell",
    services: ["Mosquito Net Distribution", "Fever Screening"],
    contactPhone: "+919863000012",
    status: "cancelled",
  },
];

export function activeCamps(camps: CampEvent[], nowIso?: string): CampEvent[] {
  const now = nowIso || new Date().toISOString();
  const today = now.slice(0, 10);
  return camps.filter((c) => c.status !== "cancelled" && Boolean(c.endDate && c.endDate >= today));
}
